### PR TITLE
Fix Clippy and RustFmt builds

### PR DESCRIPTION
**Pull request by chrisduerr**
With RustFmt I just ran a simple `cargo fmt --write-mode=overwrite` which should do the job because there are no RustFmt issues anymore and it still compiles.

Clippy was still complaining about the `license` and `license-file` attributes because only one of them should be specified. So I removed `license-file` because `license = "Apache-2.0"` should tell everyone what's going on without having to look at a different file.

Clippy also had the issue that it ran `cargo test` which failed because it couldn't link `-lxcb-randr`. So I just added `libxcb-randr0-dev` to the docker image and it should work now. I've also added both Dockerfiles so it's clear what each one is doing.

The last thing I've done is change the `pangocairo` dependency to my own repo again. Just like last time this is a quick temporary fix. I've just removed the font stuff because it works. The goal would probably be to fix it and contribute that to the official pangocairo-rs again but this should fix the CI workflow for now.

### CODE REVIEW

**Comment by chrisduerr** [comment]
It actually worked. I'll have to admit I'm a little bit impressed.

@dogamak Once you've merged this you can restart the other PRs and I'll fix the thousands of errors that will probably pop up.

**Comment by chrisduerr** [comment]
I've preemptively added a `cargo test` configuration. This is also tested by `cargo clippy` on nightly but I think having a configuration just for building all tests on stable makes sense.

**Comment by dogamak** [comment]
I know that this is an annoyingly minute detail, but I think `Dockerfile.{stable,nightly}` would be more idiomatic.

**Comment by chrisduerr** [comment]
I've changed it. I guess it's a lot easier to read like that.

**Comment by dogamak** [comment]
I think most other repositories use this naming scheme with multiple Dockerfiles.

**Pull request merged**
